# Which is equivalent to
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$cmake\
$daml\
$gleam\
$golang\
$guix_shell\
$helm\
$gradle\
$lua\
$nodejs\
$python\
$rust\
$solidity\
$terraform\
$memory_usage\
$openstack\
$nats\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[directory]
truncation_length = 0
truncate_to_repo = false